### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by fdbatista** [eceescalona/fizzbuzz#1]
Hi @eceescalona 

I am reviewing your FizzBuzz test as part of the recruitment process in CubanEngineer :)
Could you please update the README file with the instructions on how to run the tests? Maybe some command line instruction.

I don't have a C# compiler locally, but I can use a cloud-based development environment and execute your application with a terminal.

Cheers.

**Comment by eceescalona** [comment]
Hello:
Yesterday I sent a message to Shely where I told her that the exercise is already updated, and the README file has the commands to run the xUnit test.

**Comment by eceescalona** [comment]
Hi:
Yesterday I sent a message to Shely where I told her that the exercise is
already updated, and the README file has the commands to run the xUnit test.
Let me know if you need anything else.
